### ISSUE TITLE
跟着新手教程走运行的时候报错了

### ISSUE THREAD

**Issue by semgilo** [sbfkcel/puerts_cli#4]
运行的时候，不知道是哪里出错了，大佬帮忙看下
`Exception: DeveloperTools.js:29: TypeError: puer.registerBuildinModule is not a function

TypeError: puer.registerBuildinModule is not a function
    at DeveloperTools.js:29:10
    at DeveloperTools.js:65:3
Puerts.GenericDelegate.Func[T1,TResult] (T1 p1) (at Assets/Puerts/Runtime/Src/Default/JSType/GenericDelegate.cs:521)
Puerts.JsEnv.ExecuteModule (System.String specifier) (at Assets/Puerts/Runtime/Src/Default/JsEnv.cs:309)
Game.App.Awake () (at Assets/CS/App.cs:39)
`

**Comment by sbfkcel** [comment]
puerts 用的是什么版本的？尝试换成1.x的试下，2.x我还没适配

**Comment by semgilo** [comment]
暂时先不折腾这个了，我先按官网的方式简单使用
